from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from agent.core import run_research
from agent.tools.stock import get_stock_data, get_price_history
import uvicorn

app = FastAPI(
    title="Financial Research Agent API",
    description="REST API for autonomous stock research using Claude AI",
    version="1.0.0"
)


class ResearchRequest(BaseModel):
    ticker: str


class ResearchResponse(BaseModel):
    ticker: str
    brief: str


class HealthResponse(BaseModel):
    status: str
    version: str


@app.get("/health", response_model=HealthResponse)
def health_check():
    """Check if the API is running."""
    return HealthResponse(status="ok", version="1.0.0")


@app.get("/stock/{ticker}")
def get_stock(ticker: str):
    """
    Fetch live stock data for a given ticker.
    Returns price, market cap, P/E ratio, revenue, and more.
    """
    result = get_stock_data.invoke({"ticker": ticker.upper()})
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/stock/{ticker}/history")
def get_history(ticker: str):
    """
    Fetch 12 months of price history for a given ticker.
    """
    result = get_price_history.invoke({"ticker": ticker.upper()})
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.post("/research", response_model=ResearchResponse)
def research_stock(request: ResearchRequest):
    """
    Run the full AI research agent on a stock ticker.
    Returns a structured investment brief generated by Claude.
    """
    try:
        brief = run_research(request.ticker.upper())
        return ResearchResponse(ticker=request.ticker.upper(), brief=brief)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)