#!/usr/bin/env python3
"""Write terraform/oci-provided/generated-imports.tf (gitignored: it holds
OCIDs) with one `import {}` block per resource of the PROVIDED cluster that
Terraform should codify: the VCN and its networking (subnets, NSGs and
their rules, security lists, route tables, gateways, DHCP options), the OKE
cluster and its node pools. Operator only; every OCI call is a read
(list/get) through the oci CLI with its instance-principal auth.

Then `bash scripts/tf_provided.sh plan -generate-config-out=generated-config.tf`
makes Terraform write matching configuration, and iterations of
`bash scripts/tf_provided.sh plan -detailed-exitcode` drive it to zero diff.
Never apply (CLAUDE.md, the 2026-10-07 exception).

  python3 scripts/tf_provided_imports.py
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "terraform" / "oci-provided" / "generated-imports.tf"


def oci(*args: str):
    r = subprocess.run(["oci", *args], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"oci {' '.join(args[:3])} failed: {r.stderr.strip()[:300]}")
    return json.loads(r.stdout) if r.stdout.strip() else {}


def items(d):
    d = d.get("data", d)
    return d.get("items", d) if isinstance(d, dict) else d


def tf_name(prefix: str, display: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", display.lower()).strip("_")
    return f"{prefix}_{s}" if s else prefix


def cluster_id() -> str:
    cfg = json.loads(subprocess.run(["kubectl", "config", "view", "--minify", "-o", "json"],
                                    capture_output=True, text=True, check=True).stdout)
    a = cfg["users"][0]["user"]["exec"]["args"]
    return a[a.index("--cluster-id") + 1]


def blocks() -> list[tuple[str, str, str]]:
    """[(resource type, local name, import id)]"""
    out, seen = [], set()

    def add(rtype, name, rid):
        n, k = name, 2
        while (rtype, n) in seen:
            n, k = f"{name}_{k}", k + 1
        seen.add((rtype, n))
        out.append((rtype, n, rid))

    cl = oci("ce", "cluster", "get", "--cluster-id", cluster_id())["data"]
    cc, vcn_id = cl["compartment-id"], cl["vcn-id"]
    vcn = oci("network", "vcn", "get", "--vcn-id", vcn_id)["data"]
    vc = vcn["compartment-id"]
    add("oci_containerengine_cluster", tf_name("cluster", cl["name"]), cl["id"])
    for np in items(oci("ce", "node-pool", "list", "--compartment-id", cc, "--cluster-id", cl["id"], "--all")):
        add("oci_containerengine_node_pool", tf_name("pool", np["name"]), np["id"])
    add("oci_core_vcn", tf_name("vcn", vcn["display-name"]), vcn_id)
    common = ["--compartment-id", vc, "--vcn-id", vcn_id, "--all"]
    for s in items(oci("network", "subnet", "list", *common)):
        add("oci_core_subnet", tf_name("subnet", s["display-name"]), s["id"])
    for sl in items(oci("network", "security-list", "list", *common)):
        add("oci_core_security_list", tf_name("sl", sl["display-name"]), sl["id"])
    for rt in items(oci("network", "route-table", "list", *common)):
        add("oci_core_route_table", tf_name("rt", rt["display-name"]), rt["id"])
    for d in items(oci("network", "dhcp-options", "list", *common)):
        add("oci_core_dhcp_options", tf_name("dhcp", d["display-name"]), d["id"])
    for g in items(oci("network", "internet-gateway", "list", *common)):
        add("oci_core_internet_gateway", tf_name("igw", g["display-name"]), g["id"])
    for g in items(oci("network", "nat-gateway", "list", *common)):
        add("oci_core_nat_gateway", tf_name("nat", g["display-name"]), g["id"])
    for g in items(oci("network", "service-gateway", "list", *common)):
        add("oci_core_service_gateway", tf_name("sgw", g["display-name"]), g["id"])
    for n in items(oci("network", "nsg", "list", *common)):
        nname = tf_name("nsg", n["display-name"])
        add("oci_core_network_security_group", nname, n["id"])
        for i, r in enumerate(items(oci("network", "nsg", "rules", "list", "--nsg-id", n["id"], "--all"))):
            add("oci_core_network_security_group_security_rule", f"{nname}_rule_{i:02d}",
                f"networkSecurityGroups/{n['id']}/securityRules/{r['id']}")
    return out


def render(bl: list[tuple[str, str, str]]) -> str:
    head = ("# GENERATED by scripts/tf_provided_imports.py — gitignored (OCIDs).\n"
            "# Import blocks for the PROVIDED cluster: plan only, never apply.\n\n")
    return head + "".join(f'import {{\n  to = {t}.{n}\n  id = "{i}"\n}}\n\n' for t, n, i in bl)


def main() -> int:
    bl = blocks()
    OUT.write_text(render(bl), encoding="utf-8")
    counts = {}
    for t, _, _ in bl:
        counts[t] = counts.get(t, 0) + 1
    for t, c in sorted(counts.items()):
        print(f"  {c:3}  {t}")
    print(f"{len(bl)} import blocks -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
